# Mirror酱为第三方分发服务，新项目默认关闭
# 若有需要请联系 Mirror酱 开通，直接自行开启是无法使用的
# https://mirrorchyan.com/

name: mirrorchyan_release_note

on:
  workflow_dispatch:
    inputs:
      tag:
        default: ''
        required: false
  release:
    types: [edited]

jobs:
  mirrorchyan_mfa:
    runs-on: ubuntu-latest
    # Mirror酱为第三方分发服务，新项目默认关闭
    # 若有需要请联系 Mirror酱 开通，直接自行开启是无法使用的
    # https://mirrorchyan.com/
    if: ${{ github.repository_owner == 'Saratoga-Official' }}

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: MaaJR
          version_name: ${{ inputs.tag }}

          owner: Saratoga-Official
          repo: MRA
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}

  mirrorchyan_mxu:
    runs-on: ubuntu-latest
    # Mirror酱为第三方分发服务，新项目默认关闭
    # 若有需要请联系 Mirror酱 开通，直接自行开启是无法使用的
    # https://mirrorchyan.com/
    if: ${{ github.repository_owner == 'Saratoga-Official' }}

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: MaaJR-MXU
          version_name: ${{ inputs.tag }}

          owner: Saratoga-Official
          repo: MRA
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
